[package]
name = "sacn-novastar-brightness"
version = "0.1.0"
edition = "2021"

[dependencies]
sacn-unofficial = "0.9.0"
novastar-core = "0.3.1"
#novastar-core = {path = "../novastar-core"}
tokio = { version = "1.44.2", features = ["full"] }
config = "0.15.7"
